project:
  type: book

book:
  title: "Analytical Palaeobiology with Applications in R"
  author:
    - "Lewis A. Jones"
    - "Christopher D. Dean"
  date: today
  search: true
  repo-url: https://github.com/LewisAJones/analytical-palaeobiology
  repo-actions: [edit, issue]
  sharing: [twitter, facebook]
  page-footer: 
    left: "Copyright 2022, Lewis A. Jones" 
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

